// Generated by gencpp from file mp_pose/depth_image.msg
// DO NOT EDIT!


#ifndef MP_POSE_MESSAGE_DEPTH_IMAGE_H
#define MP_POSE_MESSAGE_DEPTH_IMAGE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <sensor_msgs/Image.h>
#include <sensor_msgs/Image.h>

namespace mp_pose
{
template <class ContainerAllocator>
struct depth_image_
{
  typedef depth_image_<ContainerAllocator> Type;

  depth_image_()
    : header()
    , color()
    , depth()  {
    }
  depth_image_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , color(_alloc)
    , depth(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _color_type;
  _color_type color;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _depth_type;
  _depth_type depth;





  typedef boost::shared_ptr< ::mp_pose::depth_image_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mp_pose::depth_image_<ContainerAllocator> const> ConstPtr;

}; // struct depth_image_

typedef ::mp_pose::depth_image_<std::allocator<void> > depth_image;

typedef boost::shared_ptr< ::mp_pose::depth_image > depth_imagePtr;
typedef boost::shared_ptr< ::mp_pose::depth_image const> depth_imageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mp_pose::depth_image_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mp_pose::depth_image_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mp_pose::depth_image_<ContainerAllocator1> & lhs, const ::mp_pose::depth_image_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.color == rhs.color &&
    lhs.depth == rhs.depth;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mp_pose::depth_image_<ContainerAllocator1> & lhs, const ::mp_pose::depth_image_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mp_pose

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mp_pose::depth_image_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mp_pose::depth_image_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mp_pose::depth_image_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mp_pose::depth_image_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mp_pose::depth_image_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mp_pose::depth_image_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mp_pose::depth_image_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d5a757a2153f86d20ebf7c4a06f2d17b";
  }

  static const char* value(const ::mp_pose::depth_image_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd5a757a2153f86d2ULL;
  static const uint64_t static_value2 = 0x0ebf7c4a06f2d17bULL;
};

template<class ContainerAllocator>
struct DataType< ::mp_pose::depth_image_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mp_pose/depth_image";
  }

  static const char* value(const ::mp_pose::depth_image_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mp_pose::depth_image_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Header\n"
"std_msgs/Header header\n"
"\n"
"# Data\n"
"sensor_msgs/Image color\n"
"sensor_msgs/Image depth\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
;
  }

  static const char* value(const ::mp_pose::depth_image_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mp_pose::depth_image_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.color);
      stream.next(m.depth);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct depth_image_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mp_pose::depth_image_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mp_pose::depth_image_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "color: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.color);
    s << indent << "depth: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.depth);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MP_POSE_MESSAGE_DEPTH_IMAGE_H
