// Generated by gencpp from file mp_pose/landmark.msg
// DO NOT EDIT!


#ifndef MP_POSE_MESSAGE_LANDMARK_H
#define MP_POSE_MESSAGE_LANDMARK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mp_pose
{
template <class ContainerAllocator>
struct landmark_
{
  typedef landmark_<ContainerAllocator> Type;

  landmark_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , visibility(0.0)
    , presence(0.0)  {
    }
  landmark_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , visibility(0.0)
    , presence(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _visibility_type;
  _visibility_type visibility;

   typedef float _presence_type;
  _presence_type presence;





  typedef boost::shared_ptr< ::mp_pose::landmark_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mp_pose::landmark_<ContainerAllocator> const> ConstPtr;

}; // struct landmark_

typedef ::mp_pose::landmark_<std::allocator<void> > landmark;

typedef boost::shared_ptr< ::mp_pose::landmark > landmarkPtr;
typedef boost::shared_ptr< ::mp_pose::landmark const> landmarkConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mp_pose::landmark_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mp_pose::landmark_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mp_pose::landmark_<ContainerAllocator1> & lhs, const ::mp_pose::landmark_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.visibility == rhs.visibility &&
    lhs.presence == rhs.presence;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mp_pose::landmark_<ContainerAllocator1> & lhs, const ::mp_pose::landmark_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mp_pose

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mp_pose::landmark_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mp_pose::landmark_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mp_pose::landmark_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mp_pose::landmark_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mp_pose::landmark_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mp_pose::landmark_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mp_pose::landmark_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0679b968d5e29e39a4e5b5b3f281f78a";
  }

  static const char* value(const ::mp_pose::landmark_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0679b968d5e29e39ULL;
  static const uint64_t static_value2 = 0xa4e5b5b3f281f78aULL;
};

template<class ContainerAllocator>
struct DataType< ::mp_pose::landmark_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mp_pose/landmark";
  }

  static const char* value(const ::mp_pose::landmark_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mp_pose::landmark_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 z \n"
"float32 visibility\n"
"float32 presence\n"
"# int32 keypoint\n"
;
  }

  static const char* value(const ::mp_pose::landmark_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mp_pose::landmark_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.visibility);
      stream.next(m.presence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct landmark_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mp_pose::landmark_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mp_pose::landmark_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "visibility: ";
    Printer<float>::stream(s, indent + "  ", v.visibility);
    s << indent << "presence: ";
    Printer<float>::stream(s, indent + "  ", v.presence);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MP_POSE_MESSAGE_LANDMARK_H
